version: "3.8"

services:
  rdp:
    build: ./xrdp
    ports:
      - "3389:3389"
    command: ubuntu ubuntu no
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    container_name: xrdp
  burp:
    image: retenet/burpsuite
    ports:
      - "8080:8080"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:10
    container_name: burp
  